# This is a basic workflow to help you get started with Actions

name: MYCI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1: 
    runs-on: ubuntu-latest
    services:
       nginx:
         image: nginx
         ports:
           - 8080:80
    steps:
    - uses: actions/checkout@v1
    - run: |
        node -v
        curl localhost:8080
     
